<#import "/templates/guide.adoc" as tmpl>
<#import "/templates/kc.adoc" as kc>
<#import "/templates/links.adoc" as links>

<@tmpl.guide
title="Configuring Keycloak"
summary="How to configure and start Keycloak">

This guide explains the configuration methods for Keycloak and how to start and apply the preferred configuration. It includes configuration guidelines for optimizing Keycloak for faster startup and low memory footprint.

== Configuration Sources for Keycloak
Keycloak loads the configuration from three different source types:

* command-line parameters
* environment variables
* `keycloak.conf` file located in the `conf` directory.

Configuration sources have a descending ordinal: First command-line parameters, then environment variables, then configuration file. When a configuration key is found in more than one configuration source, the used value is taken from the Source with the highest ordinal.

=== Example: Configuring the db-url-host parameter.

|===
|*Source* | *Format*

|CLI
|--db-url=cliValue

|Environment Variable
|KC_DB_URL=envVarValue

|conf/keycloak.conf
|db-url=confFileValue
|===

In the example above, the `db-url` value is set in all three configuration sources. The actual value that is used at startup would be the `cliValue`. If `--db-url=cliValue` is not used, the used value would be `KC_DB_URL=envVarValue`, and last but not least the `db-url=confFileValue` would be used when no environment variable with the same Key is present.

== Configuration Format
The configuration follows a "unified-per-source" format, that is easily translatable from one configuration source to another:

.Command-line parameter format
Values for the command-line are following the `--<key-with-dashes>=<value>` format. For some values, there's also a `-<abbreviation>=value` shorthand.

.Environment variable format
Values for environment variables are following the uppercased `KC_<key_with_underscores>=<value>` format.

.Configuration file format
Values that go into the configuration file are following the `<key-with-dashes>=<value>` format.

You can easily translate a Key/Value pair from one configuration source to the other.

You will find the relevant configuration options for a specific guide in all three formats on the table at the bottom of each guide. You can find all available options at the <@links.server id="all-config"/> guide.

The configuration source and the corresponding format you should use is use-case specific.

=== Example - Configure `db-url-host` on different configuration sources:
The following example shows how the configuration for the db url host looks for all three configuration sources:

.command-line parameter
<@kc.start parameters="--db-url-host=mykeycloakdb"/>

.environment variable
[source]
----
export KC_DB_URL_HOST=mykeycloakdb
----

.conf/keycloak.conf
[source]
----
db-url-host=mykeycloakdb
----

=== Using environment variables for configuration values
It is possible to use placeholders to resolve an environment specific value from environment variables inside the keycloak.conf file by using the `${ENV_VAR}` syntax:

[source]
----
db-url-host=${r"${MY_DB_HOST}"}
----

To specify a fallback value in case the environment variable can not be resolved, use a `:`:
[source, bash]
----
db-url-host=${r"${MY_DB_HOST:mydb}"}
----

=== Using the command-line help
Keycloak is packed with a CLI that helps you to configure Keycloak. To find out about the available configuration, invoke the following command:

<@kc.start parameters="--help"/>

Alternatively, you can find all server options at the <@links.server id="all-config"/> guide.

=== Using raw Quarkus properties
In most cases, the available configuration options should suffice to configure the server.
However, you might need to use properties directly from the underlying Quarkus framework to enable a specific behavior or capability that is missing in the keycloak configuration.

If possible, avoid using properties directly from Quarkus. These are considered unsupported by Keycloak. If your need is essential, consider opening an https://github.com/keycloak/keycloak/issues/new?assignees=&labels=kind%2Fenhancement%2Cstatus%2Ftriage&template=enhancement.yml[issue] first and help us
to improve Keycloaks configuration to fit your needs.

If that's not possible, you can configure the server using raw Quarkus properties. Perform the following steps:

. Create a `quarkus.properties` file in the `conf` directory and define any property you need.

For a complete list of Quarkus properties, see the https://quarkus.io/guides/all-config[Quarkus documentation]. Be aware that Keycloak uses a https://github.com/keycloak/keycloak/blob/main/quarkus/runtime/pom.xml#L17[subset] of quarkus extensions, so not all properties will be available.

When a quarkus property is a runtime property, it is also handled as runtime property for Keycloak. When a quarkus property is a build time property, you have to invoke a `build` for the property to be applied.

Note that some quarkus properties are mapped by the Keycloak configuration, for example `quarkus.http.port` and similar properties that are needed to configure Keycloak. If the property is used by Keycloak, defining the same underlying property key in  `quarkus.properties` will have no effect, as the keycloak configuration value takes precedence over the quarkus property value.

== Starting Keycloak
Keycloak can be started in two operation modes, `development mode` and `production mode`. Both modes offer a different set of defaults for the environment they are intended to be used.

=== Starting Keycloak in development mode
The development mode is targeted for people trying out Keycloak the first time, and get it up and running quickly. It also offers convenient defaults for developers, for example to develop a new Keycloak theme.

The development mode is started by invoking the following command:

<@kc.startdev />

.Defaults
The development mode sets the following default configuration:

* HTTP is enabled
* Strict hostname resolution is disabled
* Cache is set to local (No distributed cache mechanism used for high availability)
* Theme- and Template-caching is disabled

=== Starting Keycloak in production mode
The production mode is targeted for deployments of Keycloak into production environments.

The production mode is started by invoking the following command:

<@kc.start />

Without further configuration, this command will show you an error, because Keycloak expects to have a hostname setup and a TLS setup available when being started in production mode.

.Defaults
The production mode sets the following defaults:

* Existing hostname expected
* HTTPS/TLS certificates expected

Make sure to follow the steps outlined in the <@links.server id="configuration-production"/> guide before deploying Keycloak to production environments.

== Setup of the initial admin user
The initial admin user can be added manually using the web frontend. It needs to be accessed using a local connection (localhost) or using environment variables.

To add the initial administration user using environment variables, set `KEYCLOAK_ADMIN=<username>` for the initial administrators username and `KEYCLOAK_ADMIN_PASSWORD=<password>` for the initial administrators password.
Keycloak parses the variables at the first startup to create an initial user with administrative rights.
Once the first user with administrative rights exists, you can use the UI or the command line tool `kcadm.[sh|bat]` to create additional users.

If the initial administrator already exists and the environment variables are still present at startup, an error message stating the failed creation of the initial administrator is shown in the logs. Keycloak ignores the values and starts up correctly nevertheless.

== Optimize Keycloak runtime behaviour

It is highly recommended to optimize Keycloak for better startup times and memory consumption before deploying it into production environments. This section shows you how to do it by leveraging the `build` command.

=== Create an optimized Keycloak build
By default, when invoking the `start` or `start-dev` command, Keycloak runs a `build` under the covers for convenience reasons. The `build` performs optimizations for a subsequent startup of Keycloak. This process takes some time, and time is important, especially when running Keycloak in a containerized environment like for example Kubernetes or OpenShift.

In order to reduce the startup time , you can invoke the build beforehand,


- Optimize Keycloak
- Distinction:
- Core concepts
- Create a Closed world assumption through re-augmentation
- 2 stages: Build- and Startup
----
Done:
- Configuration sources
- Overview of diff. sources, plus order
- Using Placeholders for values
- Using the configuration Help commands
- Using raw quarkus options
- Starting Keycloak
- Development Mode
- Production Mode
- Setup the initial admin user

</@tmpl.guide>