name: Keycloak CI

on:
  push:
    branches-ignore: [main]
  # as the ci.yml contains actions that are required for PRs to be merged, it will always need to run on all PRs
  pull_request: {}
  schedule:
    - cron: '0 0 * * *'

env:
  DEFAULT_JDK_VERSION: 11

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    if: ${{ ( github.event_name != 'schedule' ) || ( github.event_name == 'schedule' && github.repository == 'keycloak/keycloak' ) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.DEFAULT_JDK_VERSION }}
          cache: 'maven'
      - name: Update maven settings
        run: mkdir -p ~/.m2 ; cp .github/settings.xml ~/.m2/

      - name: Build Keycloak
        run: |
           ./mvnw clean install -nsu -B -e -DskipTests -Pdistribution
           ./mvnw clean install -nsu -B -e -f testsuite/integration-arquillian/servers/auth-server -Pauth-server-quarkus
           ./mvnw clean install -nsu -B -e -f testsuite/integration-arquillian/servers/auth-server -Pauth-server-undertow

      - name: Store Keycloak artifacts
        id: store-keycloak
        uses: actions/upload-artifact@v3
        with:
          name: keycloak-artifacts.zip
          retention-days: 1
          path: |
            ~/.m2/repository/org/keycloak
            !~/.m2/repository/org/keycloak/**/*.tar.gz

      - name: Remove keycloak artifacts before caching
        if: steps.cache.outputs.cache-hit != 'true'
        run: rm -rf ~/.m2/repository/org/keycloak

  webauthn-test:
    name: WebAuthn Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check whether this phase should run
        run: echo "GIT_DIFF=$[ $( git diff --name-only HEAD^ | egrep -ic 'webauthn|passwordless' ) ]" >> $GITHUB_ENV

      - uses: actions/setup-java@v1
        if: ${{ github.event_name != 'pull_request' || env.GIT_DIFF != 0 }}
        with:
          java-version: ${{ env.DEFAULT_JDK_VERSION }}

      - name: Update maven settings
        if: ${{ github.event_name != 'pull_request' || env.GIT_DIFF != 0 }}
        run: mkdir -p ~/.m2 ; cp .github/settings.xml ~/.m2/

      - name: Cache Maven packages
        if: ${{ github.event_name != 'pull_request' || env.GIT_DIFF != 0 }}
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: cache-1-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-1-${{ runner.os }}-m2

      - name: Cleanup org.keycloak artifacts
        if: ${{ github.event_name != 'pull_request' || env.GIT_DIFF != 0 }}
        run: rm -rf ~/.m2/repository/org/keycloak >/dev/null || true

      - name: Download built keycloak
        if: ${{ github.event_name != 'pull_request' || env.GIT_DIFF != 0 }}
        id: download-keycloak
        uses: actions/download-artifact@v2
        with:
          path: ~/.m2/repository/org/keycloak/
          name: keycloak-artifacts.zip

      - name: Run WebAuthn tests
        if: ${{ github.event_name != 'pull_request' || env.GIT_DIFF != 0 }}
        run: |
          mvn clean install -nsu -B -Pwebauthn -f testsuite/integration-arquillian/tests/other/pom.xml -Dbrowser=chromeHeadless -Dtest=org.keycloak.testsuite.webauthn.**.*Test | misc/log/trimmer.sh
          
          TEST_RESULT=${PIPESTATUS[0]}
          find . -path '*/target/surefire-reports/*.xml' | zip -q reports-webauthn-tests.zip -@
          exit $TEST_RESULT

      - name: WebAuthn test reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: reports-webauthn-tests
          retention-days: 14
          path: reports-webauthn-tests.zip
          if-no-files-found: ignore